library(ggplot2)
library(dplyr)
library(readxl)
source("Color.R")


########## ExtFig. 3a: The number of conding sequences generated by a reverse translation of peptides ##########
eunmerate <- function(sequence) {
  sum <- 0
  for(aa in strsplit(sequence, "")[[1]]) {
    num <- -1
    if(aa == "M" || aa == "W") {
      num <- 1
    } else if(aa == "F" || aa == "Y" || aa == "H" || aa == "Q" ||
              aa == "N" || aa == "K" || aa == "D" || aa == "E" ||
              aa == "C") {
      num <- 2
    } else if(aa == "I") {
      num <- 3
    } else if(aa == "V" || aa == "P" || aa == "T" ||
              aa == "A" || aa == "G") {
      num <- 4
    } else if(aa == "L" || aa == "S" || aa == "R") {
      num <- 6
    }
    sum <- sum + log10(num)
    
  }
  
  
  
  return(sum)
}

data_MHC_I_1k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 1 k")
data_MHC_I_5k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 5 k")
data_MHC_I_10k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 10 k")
data_MHC_I_20k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 20 k")
data_MHC_I_30k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 30 k")
data_MHC_I_40k <- read_excel("SupplementaryTable1.xlsx", sheet = "9-mers 40 k")
data_MHC_I_all <- read_excel("SupplementaryTable1.xlsx", sheet = "LUAD_MHC-I")
data_MHC_II_all <- read_excel("SupplementaryTable1.xlsx", sheet = "LUAD_MHC-II")

data_MHC_I_1k$LogN <- sapply(data_MHC_I_1k$Sequence, eunmerate)
data_MHC_I_1k$Size <- "1k"
data_MHC_I_1k$Sum <- sum(10^data_MHC_I_1k$LogN)

data_MHC_I_5k$LogN <- sapply(data_MHC_I_5k$Sequence, eunmerate)
data_MHC_I_5k$Size <- "5k"
data_MHC_I_5k$Sum <- sum(10^data_MHC_I_5k$LogN)

data_MHC_I_10k$LogN <- sapply(data_MHC_I_10k$Sequence, eunmerate)
data_MHC_I_10k$Size <- "10k"
data_MHC_I_10k$Sum <- sum(10^data_MHC_I_10k$LogN)

data_MHC_I_20k$LogN <- sapply(data_MHC_I_20k$Sequence, eunmerate)
data_MHC_I_20k$Size <- "20k"
data_MHC_I_20k$Sum <- sum(10^data_MHC_I_20k$LogN)

data_MHC_I_30k$LogN <- sapply(data_MHC_I_30k$Sequence, eunmerate)
data_MHC_I_30k$Size <- "30k"
data_MHC_I_30k$Sum <- sum(10^data_MHC_I_30k$LogN)

data_MHC_I_40k$LogN <- sapply(data_MHC_I_40k$Sequence, eunmerate)
data_MHC_I_40k$Size <- "40k"
data_MHC_I_40k$Sum <- sum(10^data_MHC_I_40k$LogN)


data_MHC_I_all$LogN <- sapply(data_MHC_I_all$Sequence, eunmerate)
data_MHC_I_all$Size <- "MHC-I\n(8-12 mers)"
data_MHC_I_all$Sum <- sum(10^data_MHC_I_all$LogN)

data_MHC_II_all <- data_MHC_II_all[data_MHC_II_all$Length <= 25, ]
data_MHC_II_all$LogN <- sapply(data_MHC_II_all$Sequence, eunmerate)
data_MHC_II_all$Size <- "MHC-II\n(7-25 mers)"
data_MHC_II_all$Sum <- sum(10^data_MHC_II_all$LogN)

data_MHC_I <- rbind(data_MHC_I_1k, data_MHC_I_5k, data_MHC_I_10k, 
                    data_MHC_I_20k, data_MHC_I_30k, data_MHC_I_40k,
                    data_MHC_I_all, data_MHC_II_all)

data_MHC_I$Size <- factor(data_MHC_I$Size, levels = c("1k", "5k", "10k", "20k", "30k", "40k", "MHC-I\n(8-12 mers)", "MHC-II\n(7-25 mers)"))

plot <- ggplot(data_MHC_I, aes(x = as.factor(Size), y = log10(Sum), color = log10(Sum))) + 
  geom_point(size = 3) +
  labs(title = "", x = "", y = expression("Log"[10]("sum of coding sequences"))) + 
  guides(color = guide_legend(title = "Type")) + 
  scale_y_continuous(limits = c(8, 18), breaks = c(8, 10, 12, 14, 16, 18)) +
  theme_minimal() + 
  theme(axis.text.x = element_text(hjust = 0.5,vjust =0.5, color = "black", size = 15),
        axis.text.y = element_text(color = "black", size = 15), 
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.ticks.x = element_line(color="black"),
        axis.ticks.y = element_line(color="black"),
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15),
        legend.position = "none") +
  scale_color_gradient(low = "#4DBBD5FF",
                       high = "#E64B35FF")
plot
ggsave(filename = "ExtFig3a.png", plot = plot, height = 4, width = 4, dpi = 600)



########## ExtFig. 3b: Linear fitting ##########
fancy_scientific <- function(l) {
  # turn in to character string in scientific notation
  l <- format(l, scientific = TRUE)
  # quote the part before the exponent to keep all the digits
  l <- gsub("^(.*)e\\+", "'\\1'e", l)
  
  # turn the 'e+' into plot math format
  l <- gsub("e", "%*%10^", l)
  # return this as an expression
  l[1] <- "0"
  
  return(parse(text=l))
}

data_real_comparison <- read_excel(path = "SupplementaryTable2.xlsx", sheet = "Performance", na = "-")

data_real_comparison$Size <- factor(data_real_comparison$Size, levels = c("1k", "5k", "10k", "20k", "30k", "40k"))

summary_stats <- data_real_comparison[data_real_comparison$Tool == "BamQuery", ] %>%
  group_by(`Number of coding sequences`) %>%
  summarise(mean = mean(`Memory (GB)`),
            sd = sd(`Memory (GB)`))

summary_stats

plot_time_top <- ggplot(data_real_comparison[data_real_comparison$Tool == "BamQuery", ], 
                        aes(x = `Number of coding sequences`, y = `Time (hour)`, color = Size)) + 
  geom_boxplot(outlier.colour="black", outlier.shape=16,
               outlier.size=0.5, notch=FALSE, outliers = F) +
  geom_point(position = position_jitterdodge(jitter.width = 0.15), alpha = 0.5) +
  labs(title = "", x = "Number of coding sequences", y = "Runtime (hour)") + 
  guides(color = guide_legend(title = "Tool", nrow = 1)) +
  theme_minimal() + 
  scale_y_continuous(n.breaks = 10) +
  scale_x_continuous(labels = fancy_scientific) +
  theme(axis.text.x = element_text(hjust = 0.5, color = "black", size = 15),
        axis.text.y = element_text(color = "black", size = 15), 
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.ticks.x = element_line(color="black"),
        axis.ticks.y = element_line(color="black"),
        legend.text = element_text(size = 15), 
        legend.title = element_blank(),
        legend.position= "top") +
  geom_smooth(method = 'lm', formula = y~x+0, color=mypal[2], fill= mypal[4], alpha = 0.2) 

plot_time_top
ggsave(filename = "ExtFig3b.png", plot = plot_time_top, height = 5, width = 5, dpi = 600)